version: "3.8"
services:

    # admin:
    #     image: saline-admin-image
    #     build:
    #         context: ./admin 
    #         dockerfile: Dockerfile
    #     container_name: saline-admin
    #     restart: on-failure
    #     ports:
    #         - "3001:3000"
    #     volumes:
    #         - ./admin:/app
    #         - /app/node_modules
    #     networks:
    #         - acpSymfony

    # client:
    #     image: saline-react-image
    #     build:
    #         context: ./client
    #         dockerfile: Dockerfile
    #     container_name: saline-front
    #     volumes:
    #         - ./client:/app
    #         - /app/node_modules
    #     ports:
    #         - "3000:3000"
    #     networks:
    #         - acpSymfony


    back-office:
        container_name: saline-back-office
        build:
            context: ./back-office 
            dockerfile: Dockerfile
        restart: on-failure
        ports:
            - "3003:3000"
        volumes:
            - ./back-office:/app
            - /app/node_modules
        networks:
            - acpSymfony
            
    alpine:
        build:
            context: ./server
            dockerfile: Dockerfile
        container_name: saline-back
        restart: on-failure
        ports:
            - "1234:80"
        volumes:
            - ./server/conf/site.conf:/etc/nginx/http.d/default.conf
            - ./server/api:/var/www/html
        networks:
            - acpSymfony

    db:
        image: mariadb:10.8.2
        container_name: saline-db
        restart: always
        tty: true
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_USER: 'root'
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
        ports:
            - "3306:3306"
        networks:
            - acpSymfony

    phpmyadmin:
        image: phpmyadmin:latest
        container_name: saline-pma
        restart: always
        ports:
            - '8080:80'
        environment:
            PMA_HOST: db
            PMA_PASSWORD: ${PMA_PASS}
            PMA_ARBITRARY: 1
            PMA_USER: root
            PMA_PORT: 3306
        depends_on:
            - db
        networks:
            - acpSymfony

volumes:
    db-data:
    node_modules:


networks:
    acpSymfony:
        driver: bridge
